local data = {}

data.instrument_types = {
  "External MIDI",
  "Granular",
  "Loops",
  "Multisample",
  "One-shots",
  "Slicer",
}

data.by_instrument = {
  ["External MIDI"] = {
    contexts = {
      "Track",
      "Pass through all CCs that come in.",
    },
    by_context = {
      ["Track"] = {
        { midi_cc = 7, parameter = "Level" },
        { midi_cc = 10, parameter = "Pan" },
        { midi_cc = 91, parameter = "Reverb Send" },
        { midi_cc = 92, parameter = "Delay S end" },
      },
      ["Pass through all CCs that come in."] = {
        { midi_cc = 3, parameter = "" },
      },
    },
  },
  ["Granular"] = {
    contexts = {
      "Track",
      "Grain 1",
      "Grain 2",
      "Oscillator",
    },
    by_context = {
      ["Track"] = {
        { midi_cc = 3, parameter = "Env 2 Attack" },
        { midi_cc = 7, parameter = "Level" },
        { midi_cc = 9, parameter = "Env 2 Decay" },
        { midi_cc = 10, parameter = "Pan" },
        { midi_cc = 12, parameter = "LFO 1 Depth" },
        { midi_cc = 13, parameter = "LFO 1 Rate" },
        { midi_cc = 14, parameter = "Env 2 Release" },
        { midi_cc = 15, parameter = "LFO 2 Depth" },
        { midi_cc = 16, parameter = "LFO 2 Rate" },
        { midi_cc = 17, parameter = "Filter 2 Cutoff/Center" },
        { midi_cc = 18, parameter = "Filter 2 Resonance/Width" },
        { midi_cc = 64, parameter = "Sustain" },
        { midi_cc = 71, parameter = "Filter 1 Resonance/Width" },
        { midi_cc = 72, parameter = "Env 1 Release" },
        { midi_cc = 73, parameter = "Env 1 Attack" },
        { midi_cc = 74, parameter = "Filter 1 Cutoff/Center" },
        { midi_cc = 75, parameter = "Env 1 Decay" },
        { midi_cc = 91, parameter = "Reverb Send Reverb Send" },
        { midi_cc = 92, parameter = "Delay Send" },
      },
      ["Grain 1"] = {
        { midi_cc = 19, parameter = "Level" },
        { midi_cc = 20, parameter = "Pitch" },
        { midi_cc = 21, parameter = "Density" },
        { midi_cc = 22, parameter = "Rate" },
        { midi_cc = 23, parameter = "Grain Size" },
        { midi_cc = 24, parameter = "Window" },
        { midi_cc = 25, parameter = "Jitter" },
        { midi_cc = 26, parameter = "Play Pos" },
        { midi_cc = 27, parameter = "Speed" },
      },
      ["Grain 2"] = {
        { midi_cc = 28, parameter = "Level" },
        { midi_cc = 29, parameter = "Pitch" },
        { midi_cc = 30, parameter = "Density" },
        { midi_cc = 31, parameter = "Rate" },
        { midi_cc = 35, parameter = "Grain Size" },
        { midi_cc = 41, parameter = "Window" },
        { midi_cc = 46, parameter = "Jitter" },
        { midi_cc = 47, parameter = "Play Pos" },
        { midi_cc = 48, parameter = "Speed" },
      },
      ["Oscillator"] = {
        { midi_cc = 49, parameter = "Level" },
        { midi_cc = 50, parameter = "Pitch" },
        { midi_cc = 51, parameter = "Pulse Width" },
      },
    },
  },
  ["Loops"] = {
    contexts = {
      "Track",
      "Pad 01",
      "Pad 02",
      "Pad 03",
      "Pad 04",
      "Pad 05",
      "Pad 06",
      "Pad 07",
      "Pad 08",
      "Pad 09",
      "Pad 10",
      "Pad 11",
      "Pad 12",
      "Pad 13",
      "Pad 14",
      "Pad 15",
      "Pad 16",
    },
    by_context = {
      ["Track"] = {
        { midi_cc = 7, parameter = "Level" },
        { midi_cc = 10, parameter = "Pan" },
        { midi_cc = 91, parameter = "Reverb Send" },
        { midi_cc = 92, parameter = "Delay S end" },
      },
      ["Pad 01"] = {
        { midi_cc = 2, parameter = "Filter" },
        { midi_cc = 3, parameter = "Level" },
        { midi_cc = 28, parameter = "Pitch" },
        { midi_cc = 56, parameter = "Delay Send" },
        { midi_cc = 67, parameter = "Resonance" },
        { midi_cc = 104, parameter = "Reverb Send" },
      },
      ["Pad 02"] = {
        { midi_cc = 4, parameter = "Filter" },
        { midi_cc = 9, parameter = "Level" },
        { midi_cc = 29, parameter = "Pitch" },
        { midi_cc = 57, parameter = "Delay Send" },
        { midi_cc = 68, parameter = "Resonance" },
        { midi_cc = 105, parameter = "Reverb Send" },
      },
      ["Pad 03"] = {
        { midi_cc = 5, parameter = "Filter" },
        { midi_cc = 14, parameter = "Level" },
        { midi_cc = 30, parameter = "Pitch" },
        { midi_cc = 58, parameter = "Delay Send" },
        { midi_cc = 69, parameter = "Resonance" },
        { midi_cc = 106, parameter = "Reverb Send" },
      },
      ["Pad 04"] = {
        { midi_cc = 8, parameter = "Filter" },
        { midi_cc = 15, parameter = "Level" },
        { midi_cc = 31, parameter = "Pitch" },
        { midi_cc = 59, parameter = "Delay Send" },
        { midi_cc = 70, parameter = "Resonance" },
        { midi_cc = 107, parameter = "Reverb Send" },
      },
      ["Pad 05"] = {
        { midi_cc = 11, parameter = "Filter" },
        { midi_cc = 16, parameter = "Level" },
        { midi_cc = 35, parameter = "Pitch" },
        { midi_cc = 60, parameter = "Delay Send" },
        { midi_cc = 76, parameter = "Resonance" },
        { midi_cc = 108, parameter = "Reverb Send" },
      },
      ["Pad 06"] = {
        { midi_cc = 17, parameter = "Level" },
        { midi_cc = 34, parameter = "Filter" },
        { midi_cc = 41, parameter = "Pitch" },
        { midi_cc = 61, parameter = "Delay Send" },
        { midi_cc = 77, parameter = "Resonance" },
        { midi_cc = 109, parameter = "Reverb Send" },
      },
      ["Pad 07"] = {
        { midi_cc = 18, parameter = "Level" },
        { midi_cc = 36, parameter = "Filter" },
        { midi_cc = 46, parameter = "Pitch" },
        { midi_cc = 62, parameter = "Delay Send" },
        { midi_cc = 78, parameter = "Resonance" },
        { midi_cc = 110, parameter = "Reverb Send" },
      },
      ["Pad 08"] = {
        { midi_cc = 19, parameter = "Level" },
        { midi_cc = 37, parameter = "Filter" },
        { midi_cc = 47, parameter = "Pitch" },
        { midi_cc = 63, parameter = "Delay Send" },
        { midi_cc = 79, parameter = "Resonance" },
        { midi_cc = 111, parameter = "Reverb Send" },
      },
      ["Pad 09"] = {
        { midi_cc = 20, parameter = "Level" },
        { midi_cc = 39, parameter = "Filter" },
        { midi_cc = 48, parameter = "Pitch" },
        { midi_cc = 80, parameter = "Resonance" },
        { midi_cc = 85, parameter = "Delay Send" },
        { midi_cc = 112, parameter = "Reverb Send" },
      },
      ["Pad 10"] = {
        { midi_cc = 21, parameter = "Level" },
        { midi_cc = 40, parameter = "Filter" },
        { midi_cc = 49, parameter = "Pitch" },
        { midi_cc = 81, parameter = "Resonance" },
        { midi_cc = 86, parameter = "Delay Send" },
        { midi_cc = 113, parameter = "Reverb Send" },
      },
      ["Pad 11"] = {
        { midi_cc = 22, parameter = "Level" },
        { midi_cc = 42, parameter = "Filter" },
        { midi_cc = 50, parameter = "Pitch" },
        { midi_cc = 82, parameter = "Resonance" },
        { midi_cc = 87, parameter = "Delay Send" },
        { midi_cc = 114, parameter = "Reverb Send" },
      },
      ["Pad 12"] = {
        { midi_cc = 23, parameter = "Level" },
        { midi_cc = 43, parameter = "Filter" },
        { midi_cc = 51, parameter = "Pitch" },
        { midi_cc = 83, parameter = "Resonance" },
        { midi_cc = 88, parameter = "Delay Send" },
        { midi_cc = 115, parameter = "Reverb Send" },
      },
      ["Pad 13"] = {
        { midi_cc = 24, parameter = "Level" },
        { midi_cc = 44, parameter = "Filter" },
        { midi_cc = 52, parameter = "Pitch" },
        { midi_cc = 84, parameter = "Resonance" },
        { midi_cc = 89, parameter = "Delay Send" },
        { midi_cc = 116, parameter = "Reverb Send" },
      },
      ["Pad 14"] = {
        { midi_cc = 25, parameter = "Level" },
        { midi_cc = 45, parameter = "Filter" },
        { midi_cc = 53, parameter = "Pitch" },
        { midi_cc = 90, parameter = "Delay Send" },
        { midi_cc = 93, parameter = "Resonance" },
        { midi_cc = 117, parameter = "Reverb Send" },
      },
      ["Pad 15"] = {
        { midi_cc = 26, parameter = "Level" },
        { midi_cc = 54, parameter = "Pitch" },
        { midi_cc = 65, parameter = "Filter" },
        { midi_cc = 95, parameter = "Resonance" },
        { midi_cc = 102, parameter = "Delay Send" },
        { midi_cc = 118, parameter = "Reverb Send" },
      },
      ["Pad 16"] = {
        { midi_cc = 27, parameter = "Level" },
        { midi_cc = 55, parameter = "Pitch" },
        { midi_cc = 66, parameter = "Filter" },
        { midi_cc = 96, parameter = "Resonance" },
        { midi_cc = 103, parameter = "Delay Send" },
        { midi_cc = 119, parameter = "Reverb Send" },
      },
    },
  },
  ["Multisample"] = {
    contexts = {
      "Track",
    },
    by_context = {
      ["Track"] = {
        { midi_cc = 3, parameter = "Overdrive" },
        { midi_cc = 7, parameter = "Level" },
        { midi_cc = 10, parameter = "Pan" },
        { midi_cc = 12, parameter = "LFO Depth" },
        { midi_cc = 13, parameter = "LFO Rate" },
        { midi_cc = 64, parameter = "Sustain" },
        { midi_cc = 71, parameter = "Filter Resonance" },
        { midi_cc = 72, parameter = "Release" },
        { midi_cc = 73, parameter = "Attack" },
        { midi_cc = 74, parameter = "Filter Cutoff" },
        { midi_cc = 75, parameter = "Decay" },
        { midi_cc = 91, parameter = "Reverb Send" },
        { midi_cc = 92, parameter = "Delay Send" },
        { midi_cc = 94, parameter = "Pitch" },
      },
    },
  },
  ["One-shots"] = {
    contexts = {
      "Track",
      "Pad 01",
      "Pad 02",
      "Pad 03",
      "Pad 04",
      "Pad 05",
      "Pad 06",
      "Pad 07",
      "Pad 08",
      "Pad 09",
      "Pad 10",
      "Pad 11",
      "Pad 12",
      "Pad 13",
      "Pad 14",
      "Pad 15",
      "Pad 16",
    },
    by_context = {
      ["Track"] = {
        { midi_cc = 7, parameter = "Level" },
        { midi_cc = 10, parameter = "Pan" },
        { midi_cc = 64, parameter = "Sustain" },
        { midi_cc = 91, parameter = "Reverb Send" },
        { midi_cc = 92, parameter = "Delay Send" },
      },
      ["Pad 01"] = {
        { midi_cc = 2, parameter = "Filter" },
        { midi_cc = 3, parameter = "Level" },
        { midi_cc = 28, parameter = "Pitch" },
        { midi_cc = 56, parameter = "Delay Send" },
        { midi_cc = 67, parameter = "Resonance" },
        { midi_cc = 104, parameter = "Reverb Send" },
      },
      ["Pad 02"] = {
        { midi_cc = 4, parameter = "Filter" },
        { midi_cc = 9, parameter = "Level" },
        { midi_cc = 29, parameter = "Pitch" },
        { midi_cc = 57, parameter = "Delay Send" },
        { midi_cc = 68, parameter = "Resonance" },
        { midi_cc = 105, parameter = "Reverb Send" },
      },
      ["Pad 03"] = {
        { midi_cc = 5, parameter = "Filter" },
        { midi_cc = 14, parameter = "Level" },
        { midi_cc = 30, parameter = "Pitch" },
        { midi_cc = 58, parameter = "Delay Send" },
        { midi_cc = 69, parameter = "Resonance" },
        { midi_cc = 106, parameter = "Reverb Send" },
      },
      ["Pad 04"] = {
        { midi_cc = 8, parameter = "Filter" },
        { midi_cc = 15, parameter = "Level" },
        { midi_cc = 31, parameter = "Pitch" },
        { midi_cc = 59, parameter = "Delay Send" },
        { midi_cc = 70, parameter = "Resonance" },
        { midi_cc = 107, parameter = "Reverb Send" },
      },
      ["Pad 05"] = {
        { midi_cc = 11, parameter = "Filter" },
        { midi_cc = 16, parameter = "Level" },
        { midi_cc = 35, parameter = "Pitch" },
        { midi_cc = 60, parameter = "Delay Send" },
        { midi_cc = 76, parameter = "Resonance" },
        { midi_cc = 108, parameter = "Reverb Send" },
      },
      ["Pad 06"] = {
        { midi_cc = 17, parameter = "Level" },
        { midi_cc = 34, parameter = "Filter" },
        { midi_cc = 41, parameter = "Pitch" },
        { midi_cc = 61, parameter = "Pad Delay Send" },
        { midi_cc = 77, parameter = "Resonance" },
        { midi_cc = 109, parameter = "Reverb Send" },
      },
      ["Pad 07"] = {
        { midi_cc = 18, parameter = "Level" },
        { midi_cc = 36, parameter = "Filter" },
        { midi_cc = 46, parameter = "Pitch" },
        { midi_cc = 62, parameter = "Delay Send" },
        { midi_cc = 78, parameter = "Resonance" },
        { midi_cc = 110, parameter = "Reverb Send" },
      },
      ["Pad 08"] = {
        { midi_cc = 19, parameter = "Level" },
        { midi_cc = 37, parameter = "Filter" },
        { midi_cc = 47, parameter = "Pitch" },
        { midi_cc = 63, parameter = "Delay Send" },
        { midi_cc = 79, parameter = "Resonance" },
        { midi_cc = 111, parameter = "Reverb Send" },
      },
      ["Pad 09"] = {
        { midi_cc = 20, parameter = "Level" },
        { midi_cc = 39, parameter = "Filter" },
        { midi_cc = 48, parameter = "Pitch" },
        { midi_cc = 80, parameter = "Resonance" },
        { midi_cc = 85, parameter = "Delay Send" },
        { midi_cc = 112, parameter = "Reverb Send" },
      },
      ["Pad 10"] = {
        { midi_cc = 21, parameter = "Level" },
        { midi_cc = 40, parameter = "Filter" },
        { midi_cc = 49, parameter = "Pitch" },
        { midi_cc = 81, parameter = "Resonance" },
        { midi_cc = 86, parameter = "Delay Send" },
        { midi_cc = 113, parameter = "Reverb Send" },
      },
      ["Pad 11"] = {
        { midi_cc = 22, parameter = "Level" },
        { midi_cc = 42, parameter = "Filter" },
        { midi_cc = 50, parameter = "Pitch" },
        { midi_cc = 82, parameter = "Resonance" },
        { midi_cc = 87, parameter = "Delay Send" },
        { midi_cc = 114, parameter = "Reverb Send" },
      },
      ["Pad 12"] = {
        { midi_cc = 23, parameter = "Level" },
        { midi_cc = 43, parameter = "Filter" },
        { midi_cc = 51, parameter = "Pitch" },
        { midi_cc = 83, parameter = "Resonance" },
        { midi_cc = 88, parameter = "Delay Send" },
        { midi_cc = 115, parameter = "Reverb Send" },
      },
      ["Pad 13"] = {
        { midi_cc = 24, parameter = "Level" },
        { midi_cc = 44, parameter = "Filter" },
        { midi_cc = 52, parameter = "Pitch" },
        { midi_cc = 84, parameter = "Resonance" },
        { midi_cc = 89, parameter = "Delay Send" },
        { midi_cc = 116, parameter = "Reverb Send" },
      },
      ["Pad 14"] = {
        { midi_cc = 25, parameter = "Level" },
        { midi_cc = 45, parameter = "Filter" },
        { midi_cc = 53, parameter = "Pitch" },
        { midi_cc = 90, parameter = "Delay Send" },
        { midi_cc = 93, parameter = "Resonance" },
        { midi_cc = 117, parameter = "Reverb Send" },
      },
      ["Pad 15"] = {
        { midi_cc = 26, parameter = "Level" },
        { midi_cc = 54, parameter = "Pitch" },
        { midi_cc = 65, parameter = "Filter" },
        { midi_cc = 95, parameter = "Resonance" },
        { midi_cc = 102, parameter = "Delay Send" },
        { midi_cc = 118, parameter = "Reverb Send" },
      },
      ["Pad 16"] = {
        { midi_cc = 27, parameter = "Level" },
        { midi_cc = 55, parameter = "Pitch" },
        { midi_cc = 66, parameter = "Filter" },
        { midi_cc = 96, parameter = "Resonance" },
        { midi_cc = 103, parameter = "Delay Send" },
        { midi_cc = 119, parameter = "Reverb Send" },
      },
    },
  },
  ["Slicer"] = {
    contexts = {
      "Track",
    },
    by_context = {
      ["Track"] = {
        { midi_cc = 3, parameter = "Overdrive" },
        { midi_cc = 7, parameter = "Level" },
        { midi_cc = 10, parameter = "Pan" },
        { midi_cc = 12, parameter = "LFO Depth" },
        { midi_cc = 13, parameter = "LFO Rate" },
        { midi_cc = 71, parameter = "Filter Resonance" },
        { midi_cc = 72, parameter = "Release" },
        { midi_cc = 73, parameter = "Attack" },
        { midi_cc = 74, parameter = "Filter Cutoff" },
        { midi_cc = 75, parameter = "Decay" },
        { midi_cc = 91, parameter = "Reverb Send" },
        { midi_cc = 92, parameter = "Delay S end" },
        { midi_cc = 94, parameter = "Pitch" },
      },
    },
  },
}

return data
